favorite-ex: favorite-ex.o myfood.o
	gcc favorite-ex.o myfood.o -o favrote-ex

favorite-ex.o: favorite-ex.c
	gcc favorite-ex.c -c -o favorite-ex.o

myfood.o: myfood.c myfood.h
	gcc myfood.c -c -o myfood.o
